---
# Installs GnuPG2 and templates the configs

- name: Install gnupg (RedHat*)
  package:
    name: gnupg2
    state: latest
  when: ansible_os_family == "RedHat"

- name: Install gnupg (Arch)
  package:
    name: gnupg
    state: latest
  when: ansible_os_family == "Archlinux"

- name: Configure gpg.conf (behaviour of gpg)
  template:
    src: gpg.conf.j2
    dest: ~/.gnupg/gpg.conf

- name: Configure gpg-agent.conf (agent configuration)
  template:
    src: gpg-agent.conf.j2
    dest: ~/.gnupg/gpg-agent.conf

- name: Configure ssh-control (in order for gpg-agent to act as ssh-agent)
  template:
    src: sshcontrol.j2
    dest: ~/.gnupg/sshcontrol

- name: Copy gnupg_agent script, which makes gpg-agent responsible for ssh-auth
  copy:
    src: "{{ role_path }}/files/gpg_agent"
    dest: ~/.gnupg/gpg_agent
    mode: 0700

